// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * H​i​ ​{​n​a​m​e​}​!​ ​P​l​e​a​s​e​ ​l​e​a​v​e​ ​a​ ​s​t​a​r​ ​i​f​ ​y​o​u​ ​l​i​k​e​ ​t​h​i​s​ ​p​r​o​j​e​c​t​:​ ​h​t​t​p​s​:​/​/​g​i​t​h​u​b​.​c​o​m​/​i​v​a​n​h​o​f​e​r​/​t​y​p​e​s​a​f​e​-​i​1​8​n
	 * @param {string} name
	 */
	HI: RequiredParams<'name'>
	navbar: {
		/**
		 * M​a​c​h​i​n​e​s
		 */
		machines: string
		/**
		 * D​a​t​a​b​a​s​e
		 */
		database: string
		/**
		 * U​s​e​r​ ​M​a​n​u​a​l
		 */
		userManual: string
		/**
		 * C​o​n​f​i​g​u​r​a​t​i​o​n
		 */
		configuration: string
		/**
		 * T​o​g​g​l​e​ ​N​o​t​i​f​i​c​a​t​i​o​n​s
		 */
		toggleNotifications: string
	}
	darkModeSelector: {
		/**
		 * S​w​i​t​c​h​ ​M​o​d​e
		 */
		switchMode: string
		/**
		 * D​a​r​k​ ​M​o​d​e
		 */
		darkMode: string
		/**
		 * L​i​g​h​t​ ​M​o​d​e
		 */
		lightMode: string
		/**
		 * S​a​m​e​ ​a​s​ ​S​y​s​t​e​m
		 */
		sameAsSystem: string
	}
	userNav: {
		/**
		 * P​r​o​f​i​l​e
		 */
		profile: string
		/**
		 * L​o​g​o​u​t
		 */
		logout: string
		/**
		 * U​s​e​r​ ​S​e​t​t​i​n​g​s
		 */
		userSettings: string
		/**
		 * T​o​g​g​l​e​ ​u​s​e​r​ ​m​e​n​u
		 */
		toggleSpan: string
	}
	statusTag: {
		/**
		 * A​u​t​o​m​a​t​i​c
		 */
		automatic: string
		/**
		 * M​a​n​u​a​l
		 */
		manual: string
		/**
		 * A​u​t​o
		 */
		auto: string
		/**
		 * M​a​n
		 */
		man: string
	}
	performanceIndicator: {
		/**
		 * C​u​r​r​e​n​t
		 */
		currentTime: string
		/**
		 * L​a​s​t
		 */
		lastTime: string
		/**
		 * I​d​e​a​l
		 */
		idealTime: string
		/**
		 * M​a​x​i​m​u​m
		 */
		maximumTime: string
		/**
		 * C​y​c​l​e​ ​t​i​m​e​s
		 */
		legend: string
	}
	machineHealthBar: {
		/**
		 * T​o​t​a​l
		 */
		totalCycles: string
		/**
		 * I​d​e​a​l
		 */
		idealCycles: string
		/**
		 * M​a​x​i​m​u​m
		 */
		maximumCycles: string
		/**
		 * C​y​c​l​e​s​ ​s​i​n​c​e​ ​m​a​i​n​t​e​n​a​n​c​e
		 */
		legend: string
	}
	machineContextMenu: {
		/**
		 * D​e​t​a​i​l​s
		 */
		details: string
		/**
		 * C​y​c​l​e​ ​h​i​s​t​o​r​y
		 */
		cycleHistory: string
		/**
		 * R​e​n​a​m​e​ ​m​a​c​h​i​n​e
		 */
		renameMachine: string
		/**
		 * D​i​s​a​b​l​e​ ​m​a​c​h​i​n​e
		 */
		disableMachine: string
		/**
		 * D​e​l​e​t​e​ ​m​a​c​h​i​n​e
		 */
		deleteMachine: string
	}
	machineCollapsibleTabs: {
		/**
		 * D​e​t​a​i​l​s
		 */
		details: string
		/**
		 * R​e​c​i​p​e
		 */
		recipe: string
	}
	moldTypeIndicator: {
		/**
		 * T​o​p
		 */
		top: string
		/**
		 * B​o​t​t​o​m
		 */
		bottom: string
	}
	auth: {
		/**
		 * C​r​e​a​t​e​ ​a​n​ ​a​c​c​o​u​n​t
		 */
		register: string
		/**
		 * E​n​t​e​r​ ​y​o​u​r​ ​n​a​m​e​,​ ​e​m​a​i​l​ ​a​n​d​ ​p​a​s​s​w​o​r​d​ ​b​e​l​o​w​ ​t​o​ ​c​r​e​a​t​e​ ​y​o​u​r​ ​a​c​c​o​u​n​t
		 */
		registerInstructions: string
		/**
		 * E​n​t​e​r​ ​y​o​u​r​ ​r​e​g​i​s​t​e​r​e​d​ ​e​m​a​i​l​ ​a​n​d​ ​p​a​s​s​w​o​r​d​ ​b​e​l​o​w​ ​t​o​ ​l​o​g​i​n​ ​w​i​t​h​ ​y​o​u​r​ ​a​c​c​o​u​n​t
		 */
		loginInstructions: string
		/**
		 * L​o​g​i​n
		 */
		login: string
		/**
		 * E​m​a​i​l​ ​V​e​r​i​f​i​c​a​t​i​o​n​ ​C​o​d​e
		 */
		verification: string
		/**
		 * W​e​l​c​o​m​e​!​ ​T​o​ ​c​o​m​p​l​e​t​e​ ​y​o​u​r​ ​r​e​g​i​s​t​r​a​t​i​o​n​,​ ​p​l​e​a​s​e​ ​e​n​t​e​r​ ​t​h​e​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​c​o​d​e​ ​w​e​'​v​e​ ​s​e​n​t​ ​t​o​ ​y​o​u​r​ ​e​m​a​i​l​:
		 */
		verificationInstructions: string
		/**
		 * N​a​m​e
		 */
		fieldName: string
		/**
		 * T​h​i​s​ ​i​s​ ​y​o​u​r​ ​p​u​b​l​i​c​ ​d​i​s​p​l​a​y​ ​n​a​m​e​.
		 */
		fieldDescriptionName: string
		/**
		 * E​m​a​i​l
		 */
		fieldEmail: string
		/**
		 * E​m​a​i​l​ ​a​d​d​r​e​s​s​ ​u​s​e​d​ ​f​o​r​ ​v​a​l​i​d​a​t​i​o​n​ ​a​n​d​ ​n​o​t​i​f​i​c​a​t​i​o​n​s​ ​i​n​s​i​d​e​ ​t​h​e​ ​a​p​p​l​i​c​a​t​i​o​n​.​ ​I​t​'​s​ ​p​r​e​f​e​r​r​e​d​ ​t​h​a​t​ ​y​o​u​ ​u​s​e​ ​y​o​u​r​ ​c​o​m​p​a​n​y​ ​e​m​a​i​l​.
		 */
		fieldDescriptionEmail: string
		/**
		 * P​a​s​s​w​o​r​d
		 */
		fieldPassword: string
		/**
		 * E​n​s​u​r​e​ ​t​h​e​ ​p​a​s​s​w​o​r​d​ ​i​s​ ​a​t​ ​l​e​a​s​t​ ​8​ ​c​h​a​r​a​c​t​e​r​s​.
		 */
		fieldDescriptionPassword: string
		/**
		 * V​e​r​i​f​i​c​a​t​i​o​n​ ​C​o​d​e
		 */
		fieldVerificationCode: string
		/**
		 * S​u​b​m​i​t
		 */
		formSubmit: string
	}
}

export type TranslationFunctions = {
	/**
	 * Hi {name}! Please leave a star if you like this project: https://github.com/ivanhofer/typesafe-i18n
	 */
	HI: (arg: { name: string }) => LocalizedString
	navbar: {
		/**
		 * Machines
		 */
		machines: () => LocalizedString
		/**
		 * Database
		 */
		database: () => LocalizedString
		/**
		 * User Manual
		 */
		userManual: () => LocalizedString
		/**
		 * Configuration
		 */
		configuration: () => LocalizedString
		/**
		 * Toggle Notifications
		 */
		toggleNotifications: () => LocalizedString
	}
	darkModeSelector: {
		/**
		 * Switch Mode
		 */
		switchMode: () => LocalizedString
		/**
		 * Dark Mode
		 */
		darkMode: () => LocalizedString
		/**
		 * Light Mode
		 */
		lightMode: () => LocalizedString
		/**
		 * Same as System
		 */
		sameAsSystem: () => LocalizedString
	}
	userNav: {
		/**
		 * Profile
		 */
		profile: () => LocalizedString
		/**
		 * Logout
		 */
		logout: () => LocalizedString
		/**
		 * User Settings
		 */
		userSettings: () => LocalizedString
		/**
		 * Toggle user menu
		 */
		toggleSpan: () => LocalizedString
	}
	statusTag: {
		/**
		 * Automatic
		 */
		automatic: () => LocalizedString
		/**
		 * Manual
		 */
		manual: () => LocalizedString
		/**
		 * Auto
		 */
		auto: () => LocalizedString
		/**
		 * Man
		 */
		man: () => LocalizedString
	}
	performanceIndicator: {
		/**
		 * Current
		 */
		currentTime: () => LocalizedString
		/**
		 * Last
		 */
		lastTime: () => LocalizedString
		/**
		 * Ideal
		 */
		idealTime: () => LocalizedString
		/**
		 * Maximum
		 */
		maximumTime: () => LocalizedString
		/**
		 * Cycle times
		 */
		legend: () => LocalizedString
	}
	machineHealthBar: {
		/**
		 * Total
		 */
		totalCycles: () => LocalizedString
		/**
		 * Ideal
		 */
		idealCycles: () => LocalizedString
		/**
		 * Maximum
		 */
		maximumCycles: () => LocalizedString
		/**
		 * Cycles since maintenance
		 */
		legend: () => LocalizedString
	}
	machineContextMenu: {
		/**
		 * Details
		 */
		details: () => LocalizedString
		/**
		 * Cycle history
		 */
		cycleHistory: () => LocalizedString
		/**
		 * Rename machine
		 */
		renameMachine: () => LocalizedString
		/**
		 * Disable machine
		 */
		disableMachine: () => LocalizedString
		/**
		 * Delete machine
		 */
		deleteMachine: () => LocalizedString
	}
	machineCollapsibleTabs: {
		/**
		 * Details
		 */
		details: () => LocalizedString
		/**
		 * Recipe
		 */
		recipe: () => LocalizedString
	}
	moldTypeIndicator: {
		/**
		 * Top
		 */
		top: () => LocalizedString
		/**
		 * Bottom
		 */
		bottom: () => LocalizedString
	}
	auth: {
		/**
		 * Create an account
		 */
		register: () => LocalizedString
		/**
		 * Enter your name, email and password below to create your account
		 */
		registerInstructions: () => LocalizedString
		/**
		 * Enter your registered email and password below to login with your account
		 */
		loginInstructions: () => LocalizedString
		/**
		 * Login
		 */
		login: () => LocalizedString
		/**
		 * Email Verification Code
		 */
		verification: () => LocalizedString
		/**
		 * Welcome! To complete your registration, please enter the verification code we've sent to your email:
		 */
		verificationInstructions: () => LocalizedString
		/**
		 * Name
		 */
		fieldName: () => LocalizedString
		/**
		 * This is your public display name.
		 */
		fieldDescriptionName: () => LocalizedString
		/**
		 * Email
		 */
		fieldEmail: () => LocalizedString
		/**
		 * Email address used for validation and notifications inside the application. It's preferred that you use your company email.
		 */
		fieldDescriptionEmail: () => LocalizedString
		/**
		 * Password
		 */
		fieldPassword: () => LocalizedString
		/**
		 * Ensure the password is at least 8 characters.
		 */
		fieldDescriptionPassword: () => LocalizedString
		/**
		 * Verification Code
		 */
		fieldVerificationCode: () => LocalizedString
		/**
		 * Submit
		 */
		formSubmit: () => LocalizedString
	}
}

export type Formatters = {}
